[
  {
    "id": "1",
    "name": "Toyota Camry",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/1Series/3/5Hatchback%20Sport/bmw_20118isporthb3b_lowaggressive.png?width=300",
    "brand": "Toyota",
    "year": 2022,
    "price": 24425,
    "mileage": 10000,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "2",
    "name": "Honda Accord",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/2SeriesActiveTourer/2/5MiniMPV%20MSport/bmw_22218iactivetourermsportmp2b_lowaggressive.png?width=300",
    "brand": "Honda",
    "year": 2021,
    "price": 24970,
    "mileage": 12000,
    "color": "Black",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "3",
    "name": "Ford Mustang",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/2SeriesGranCoupe/2/4Sedan%20MSport/bmw_20220dgrancpmsportsd2b_lowaggressive.png?width=300",
    "brand": "Ford",
    "year": 2020,
    "price": 27155,
    "mileage": 15000,
    "color": "Red",
    "transmission": "Manual",
    "fuelType": "Gasoline"
  },
  {
    "id": "4",
    "name": "Chevrolet Camaro",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/3Series/7/4Sedan%20Msport/bmw_22318imsport4wdsd7re_lowaggressive.png?width=300",
    "brand": "Chevrolet",
    "year": 2019,
    "price": 25000,
    "mileage": 20000,
    "color": "Yellow",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "5",
    "name": "BMW 3 Series",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/3SeriesTouring/7/5Wagon%20M340d/bmw_23340dmtouring4wdwg7rb_lowaggressive.png?width=300",
    "brand": "BMW",
    "year": 2021,
    "price": 41250,
    "mileage": 8000,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "6",
    "name": "BMW 4 Series",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/4Series/2/2Coupe%20MSport/bmw_21430imsportcp2b_lowaggressive.png?width=300",
    "brand": "BMW",
    "year": 2022,
    "price": 39900,
    "mileage": 7000,
    "color": "Gray",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "7",
    "name": "Mercedes-Benz C-Class",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/4SeriesCabrio/2/2Convertible%20MSport/bmw_23420imsportcv2b_lowaggressive.png?width=300",
    "brand": "BMW",
    "year": 2022,
    "price": 41400,
    "mileage": 5000,
    "color": "Silver",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "8",
    "name": "Tesla Model 3",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/5Series/8/4Sedan%20MSport/bmw_24520ikitmsportsd8b_lowaggressive.png?width=300",
    "brand": "Tesla",
    "year": 2022,
    "price": 46990,
    "mileage": 3000,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Electric"
  },
  {
    "id": "9",
    "name": "Nissan Altima",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/7Seriessaloonpluginhybrid/7/4Sedan%20M760Exdrive/bmw_24m760exdrivephevsd7b_lowaggressive.png?width=300",
    "brand": "Nissan",
    "year": 2021,
    "price": 24500,
    "mileage": 15000,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "10",
    "name": "Hyundai Sonata",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/8Series/2/2Coupe%20840i/bmw_23840icoupe4wdcp2re_lowaggressive.png?width=300",
    "brand": "Hyundai",
    "year": 2021,
    "price": 23000,
    "mileage": 12000,
    "color": "Black",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "11",
    "name": "Kia Optima",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/8SeriesGranCoupe/2/4Sedan%20M850i/bmw_22850imgrancp4wdsd2fb_lowaggressive.png?width=300",
    "brand": "Kia",
    "year": 2020,
    "price": 22000,
    "mileage": 17000,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "12",
    "name": "Mazda 6",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/i4/1/5Hatchback%20M50/bmw_22i4grancpm50awdhb1b_lowaggressive.png?width=300",
    "brand": "Mazda",
    "year": 2022,
    "price": 24000,
    "mileage": 8000,
    "color": "Gray",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "13",
    "name": "Volkswagen Passat",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/I5/1/4Sedan%20Msport/bmw_24i5edrive40evkitmsportsd1b_lowaggressive.png?width=300",
    "brand": "Volkswagen",
    "year": 2021,
    "price": 28000,
    "mileage": 6000,
    "color": "Black",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "14",
    "name": "Subaru Legacy",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/i7/1/4Sedan%20MSport/bmw_23i7ev4wd60msportsd1b_lowaggressive.png?width=300",
    "brand": "Subaru",
    "year": 2022,
    "price": 26500,
    "mileage": 5000,
    "color": "Silver",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "15",
    "name": "Chrysler 300",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/iX/1/5SUV%20xDrive40/bmw_24ixevxdrive40basesu1bfr_lowaggressive.png?width=300",
    "brand": "Chrysler",
    "year": 2020,
    "price": 30000,
    "mileage": 25000,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "16",
    "name": "Volvo S60",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/iX1/1/5Suv%20Xline/bmw_24ix1edrive20evxlinesu1fb_lowaggressive.png?width=300",
    "brand": "Volvo",
    "year": 2022,
    "price": 38000,
    "mileage": 4000,
    "color": "Black",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "17",
    "name": "Jaguar XF",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/bfimg/BMW/iX2/bmw_ix2_lowaggressive.png?width=300",
    "brand": "Jaguar",
    "year": 2021,
    "price": 51000,
    "mileage": 7000,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "18",
    "name": "Porsche Panamera",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/ix3/3/5SUV%20EVBase/bmw_22ix3evinspiringsu3fb_lowaggressive.png?width=300",
    "brand": "Porsche",
    "year": 2022,
    "price": 87000,
    "mileage": 3000,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "19",
    "name": "Lexus ES",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/M2Coupe/2/2Coupe%20Base/bmw_24m2coupecp2b_lowaggressive.png?width=300",
    "brand": "Lexus",
    "year": 2021,
    "price": 40000,
    "mileage": 5000,
    "color": "Gray",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "20",
    "name": "Infiniti Q50",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/3SeriesTouring/6/5Wagon%20M3Competition/bmw_23m3comptouring4wdwg6fb_lowaggressive.png?width=300",
    "brand": "Infiniti",
    "year": 2021,
    "price": 42000,
    "mileage": 8000,
    "color": "Silver",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "21",
    "name": "Genesis G70",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/M4Cabrio/2/2Convertible%20xDrive/bmw_24m4compxdrivecv2rb_lowaggressive.png?width=300",
    "brand": "Genesis",
    "year": 2022,
    "price": 45000,
    "mileage": 3000,
    "color": "red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "22",
    "name": "Cadillac CT5",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/M8GranCoupe/1/4Sedan%20Competition/bmw_20m8comptngrancpsd1b_lowaggressive.png?width=300",
    "brand": "Cadillac",
    "year": 2021,
    "price": 47000,
    "mileage": 10000,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "23",
    "name": "Acura TLX",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/X3/3/5SUV%20Msport_4wd/bmw_24x3msport20d4wdsu3rbfr_lowaggressive.png?width=300",
    "brand": "Acura",
    "year": 2021,
    "price": 38000,
    "mileage": 7000,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "24",
    "name": "Lincoln MKZ",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/X4/2/5SUV%20M40d/bmw_23x4m40d4wdsu2fb_lowaggressive.png?width=300",
    "brand": "Lincoln",
    "year": 2020,
    "price": 42000,
    "mileage": 12000,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "25",
    "name": "Alfa Romeo Giulia",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/XMPluginHybrid/1/5SUV%20XM/bmw_23xmphev4wdsu1b_lowaggressive.png?width=300",
    "brand": "Alfa Romeo",
    "year": 2022,
    "price": 50000,
    "mileage": 4000,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "26",
    "name": "Maserati Ghibli",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/BMW/X6/3/5SUV%20MSport/bmw_24x6xdrive30dmsprtsu3re_lowaggressive.png?width=300",
    "brand": "Maserati",
    "year": 2022,
    "price": 75000,
    "mileage": 3000,
    "color": "Black",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "27",
    "name": "Bentley Flying Spur",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Audi/RS3/4/4Sedan%20Base/audi_22rs3awdsd4b_lowaggressive.png?width=300",
    "brand": "Bentley",
    "year": 2022,
    "price": 200000,
    "mileage": 2000,
    "color": "red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "28",
    "name": "Rolls-Royce Ghost",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Audi/RS3Sportback/4/5Hatchback%20RS3/audi_22rs3sprtbkh4wdb4b_lowaggressive.png?width=300",
    "brand": "Rolls-Royce",
    "year": 2022,
    "price": 330000,
    "mileage": 1000,
    "color": "Silver",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "29",
    "name": "Aston Martin DB11",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Audi/RSQ8/1/5SUV%20BaseAWD/audi_22rsq8awdsu1b_lowaggressive.png?width=300",
    "brand": "Aston Martin",
    "year": 2022,
    "price": 220000,
    "mileage": 2000,
    "color": "Green",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "30",
    "name": "Ferrari 488",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Audi/Q4Etron/1/5Suv%20Evsline_2Wd/audi_24q4etronevslinesu1bfr_lowaggressive.png?width=300",
    "brand": "Ferrari",
    "year": 2022,
    "price": 280000,
    "mileage": 1000,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "31",
    "name": "Lamborghini Huracan",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Audi/A1Sportback/2/5Hatchback%20Sport/audi_24a1sportbackadvhb2fbfr_lowaggressive.png?width=300",
    "brand": "Lamborghini",
    "year": 2022,
    "price": 350000,
    "mileage": 800,
    "color": "Yellow",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "32",
    "name": "McLaren 720S",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/smart/EQfortwo/3/2Convertible%20exclusive/smart_20eqfor2cmfrtpluscv3fb_lowaggressive.png?width=300",
    "brand": "McLaren",
    "year": 2022,
    "price": 400000,
    "mileage": 600,
    "color": "Orange",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "33",
    "name": "Bugatti Chiron",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/smart/EQforfour/2/5Hatchback%20PrimeExclusive/smart_20eqfor4cmfrtplushb2fb_lowaggressive.png?width=300",
    "brand": "Bugatti",
    "year": 2022,
    "price": 3000000,
    "mileage": 200,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "34",
    "name": "Pagani Huayra",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Tesla/ModelS/1/5Hatchback%20Plaid/tesla_21modelsplaid4wdhb1re_lowaggressive.png?width=300",
    "brand": "Pagani",
    "year": 2022,
    "price": 3200000,
    "mileage": 100,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "35",
    "name": "Koenigsegg Jesko",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ford/FocusST/4/5Hatchback%20ST/ford_23focussthb4fb_lowaggressive.png?width=300",
    "brand": "Koenigsegg",
    "year": 2022,
    "price": 3400000,
    "mileage": 50,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "36",
    "name": "Rimac C_Two",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ford/Mustang/6/2Coupe%20MACH1/ford_21mustangmach1cp6rb_lowaggressive.png?width=300",
    "brand": "Rimac",
    "year": 2022,
    "price": 2000000,
    "mileage": 300,
    "color": "Gray",
    "transmission": "Automatic",
    "fuelType": "Electric"
  },
  {
    "id": "37",
    "name": "Tesla Roadster",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ford/SMax/2/5MiniMPV%20HEVSTLine/ford_21smaxhevstlinemp2fb_lowaggressive.png?width=300",
    "brand": "Tesla",
    "year": 2022,
    "price": 250000,
    "mileage": 500,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Electric"
  },
  {
    "id": "38",
    "name": "Porsche 911",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ford/TourneoConnect/3/5MiniMPV%20Active/ford_22tourneocnctactv7plmp3b_lowaggressive.png?width=300",
    "brand": "Porsche",
    "year": 2022,
    "price": 150000,
    "mileage": 1000,
    "color": "Silver",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "39",
    "name": "Chevrolet Corvette",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ford/TourneoCourier/2/5MiniMPV%20Active/ford_24tourneocourieractivemp2b_lowaggressive.png?width=300",
    "brand": "Chevrolet",
    "year": 2022,
    "price": 70000,
    "mileage": 2000,
    "color": "Yellow",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "40",
    "name": "Dodge Challenger",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ford/Puma/1/5SUV%20MHEVSTLine/ford_24pumamhevstlinesu1bfr_lowaggressive.png?width=300",
    "brand": "Dodge",
    "year": 2022,
    "price": 60000,
    "mileage": 3000,
    "color": "Red",
    "transmission": "Manual",
    "fuelType": "Gasoline"
  },
  {
    "id": "41",
    "name": "Ford GT",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Citroen/C3/3/5Hatchback%20Max/citroen_24c3maxhb3fb_lowaggressive.png?width=300",
    "brand": "Ford",
    "year": 2022,
    "price": 500000,
    "mileage": 500,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "42",
    "name": "Nissan GT-R",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Citroen/C3Aircorss/2/5SUV%20Shine/citroen_22c3aircrossshinesu2fb_lowaggressive.png?width=300",
    "brand": "Nissan",
    "year": 2022,
    "price": 113540,
    "mileage": 1000,
    "color": "Gray",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "43",
    "name": "Toyota Supra",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Citroen/C5X/1/5Hatchback%20Max/citroen_24c5xphevmaxhb1fc_lowaggressive.png?width=300",
    "brand": "Toyota",
    "year": 2022,
    "price": 52000,
    "mileage": 2000,
    "color": "Yellow",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "44",
    "name": "Lexus LC",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Ds/Ds4/2/5Hatchback%20Opera/ds_24ds4etoilecuirnappahb2bfr_lowaggressive.png?width=300",
    "brand": "Lexus",
    "year": 2022,
    "price": 94000,
    "mileage": 500,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "45",
    "name": "Mercedes-Benz S-Class",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/AlfaRomeo/Stelvio/1/5SUV%20Veloce/alfaromeo_23stelvioq4velocesu1rb_lowaggressive.png?width=300",
    "brand": "Mercedes-Benz",
    "year": 2022,
    "price": 110000,
    "mileage": 800,
    "color": "Black",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "46",
    "name": "BMW M8",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/AlfaRomeo/Tonale/1/5SUV%20Sprint/alfaromeo_24tonalesprintsu1bfr_lowaggressive.png?width=300",
    "brand": "BMW",
    "year": 2022,
    "price": 133000,
    "mileage": 600,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "47",
    "name": "Audi R8",
    "imageUrl": "https://cdn.pixabay.com/photo/2017/03/27/14/56/auto-2179220_1280.jpg",
    "brand": "Audi",
    "year": 2022,
    "price": 142700,
    "mileage": 400,
    "color": "Silver",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "48",
    "name": "Jaguar F-Type",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Abarth/500e/3/3Hatchback%20Turismo/abarth_23500eevturismoha3b_lowaggressive.png?width=300",
    "brand": "Jaguar",
    "year": 2022,
    "price": 81000,
    "mileage": 1500,
    "color": "Blue",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "49",
    "name": "Aston Martin Vantage",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Abarth/595/2/3Hatchback%20Turismo/abarth_18595turismoha2fb_lowaggressive.png?width=300",
    "brand": "Aston Martin",
    "year": 2022,
    "price": 153000,
    "mileage": 500,
    "color": "Green",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  },
  {
    "id": "50",
    "name": "Ferrari Portofino",
    "imageUrl": "https://cdn.cars2buy.co.uk/assets/images/vehicles/Pix/Bentley/ContinentalGTC/3/2Convertible%20Anniversary/bentley_22contintlgtc100aniv4wdcv3bc_lowaggressive.png?width=300",
    "brand": "Ferrari",
    "year": 2022,
    "price": 218750,
    "mileage": 300,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline"
  }
];

// todo --> new today ----------------------------------------------------

[
  {
    "id": "110ea",
    "name": "Toyota C-HR",
    "imageUrl": "https://www.leaseloco.com/_next/image?url=https%3A%2F%2Fvehicle-images.leaseloco.com%2F2024%2F6%2F17%2F15-13%2F9996c6eb81daf64f6eb3980d30265eb1%2FPix%2FToyota%2FCHRHybrid%2F5SUV%20PremiereEdition%2Ftoyota_24chrhevpremieresu2b_sideview.png&w=384&q=75",
    "brand": "Toyota",
    "year": 2024,
    "price": 244259,
    "mileage": 8000,
    "color": "Gold",
    "transmission": "Automatic",
    "fuelType": "Gasoline",
    "description": "The Toyota C-HR is a reliable and fuel-efficient mid-size sedan that offers a comfortable ride and plenty of interior space. It's a great choice for families and commuters alike."
  },
  {
    "id": "320fa",
    "name": "Hyundai Kona Electric",
    "imageUrl": "https://www.leaseloco.com/_next/image?url=https%3A%2F%2Fvehicle-images.leaseloco.com%2F2024%2F6%2F17%2F15-13%2F9996c6eb81daf64f6eb3980d30265eb1%2FPix%2FHyundai%2FKonaElectric%2F5SUV%20Advance%2Fhyundai_24konaevfeelsu2b_sideview.png&w=384&q=75",
    "brand": "Hyundai",
    "year": 2024,
    "price": 354259,
    "mileage": 5000,
    "color": "Red",
    "transmission": "Automatic",
    "fuelType": "Gasoline",
    "description": "The Hyundai Kona Electric is a high-performance sports car that delivers breathtaking acceleration and handling. It's known for its iconic design, powerful engine, and exhilarating driving experience."
  },
  {
    "id": "alx23",
    "name": "CUPRA Born 150kW",
    "imageUrl": "https://www.leaseloco.com/_next/image?url=https%3A%2F%2Fvehicle-images.leaseloco.com%2F2024%2F6%2F17%2F15-13%2F9996c6eb81daf64f6eb3980d30265eb1%2FPix%2FCupra%2FBornEV%2F5Hatchback%20V1%2Fcupra_24bornevstandardhb1b_sideview.png&w=384&q=75",
    "brand": "CUPRA",
    "year": 2024,
    "price": 441899,
    "mileage": 6000,
    "color": "White",
    "transmission": "Automatic",
    "fuelType": "Gasoline",
    "description": "The CUPRA Born 150kW is an iconic sports car known for its timeless design, exceptional handling, and powerful engines. It offers a thrilling driving experience and a rich heritage."
  }
]
